version: 2.1

workflows:
  ci-pipeline:
    jobs:
      - movie-review-pipeline

jobs:
  movie-review-pipeline:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pip-{{ checksum "requirements.txt" }}
            - v1-pip-

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - save_cache:
          key: v1-pip-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Run pipeline
          command: dvc repro
